permalink: "/:year/:month/:day/:title/"
markdown: "rdiscount"
exclude: ["Rakefile", "README.markdown", "Gemfile", "Gemfile.lock", "scripts", "_secret.yml"]
source: "source"
destination: "public"
plugins: "plugins"
paginate: 10

replace_absolute: "/media/"
absolute_path: "/jekyll-instagram"
root: "lukekarrys.github.io"
instagram_client_id: "4f82d0b740ee4556b371647f1193a85e"
instagram_redirect_uri: "http://lukekarrys.github.io/jekyll-instagram"
max_caption_created_diff: 600
