permalink: /:year/:month/:day/:title/
markdown: rdiscount
exclude: ["gettoken.sh", "Rakefile", "README.markdown", "Gemfile", "Gemfile.lock", "deploy.sh"]

root: localhost:9000
instagram_client: 4f82d0b740ee4556b371647f1193a85e