# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
permalink: /:year/:month/:day/:title/
source: source
destination: public
plugins: plugins
category_dir: categories
markdown: rdiscount

paginate: 5                     # Posts per page on the blog index
pagination_dir:  ''             # Directory base for pagination URLs eg. /blog/page/2/