permalink: "/:year/:month/:day/:title/"
markdown: "rdiscount"
exclude: ["Rakefile", "README.markdown", "Gemfile", "Gemfile.lock", "scripts"]
source: "source"
destination: "public"
root: "instagram.lukelov.es"
instagram_client: "4f82d0b740ee4556b371647f1193a85e"